# CloudOps Agent Kubernetes Manifests
# 
# Prerequisites:
# 1. Create the namespace: kubectl create namespace cloudops-agent
# 2. Create the secret with your API key:
#    kubectl create secret generic cloudops-agent-secret \
#      --from-literal=API_KEY=your-api-key-here \
#      -n cloudops-agent
#
# Then apply this file:
#    kubectl apply -f cloudops-agent-k8s-manifests.yaml -n cloudops-agent

---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudops-agent
  labels:
    app.kubernetes.io/name: cloudops-agent

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudops-agent
  namespace: cloudops-agent
  labels:
    app.kubernetes.io/name: cloudops-agent

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudops-agent-config
  namespace: cloudops-agent
  labels:
    app.kubernetes.io/name: cloudops-agent
data:
  # IMPORTANT: Update these values with your configuration
  API_URL: "https://your-cloudops-api.example.com"
  POOL_ID: "your-pool-id-here"
  MAX_PARALLEL_JOBS: "2"
  HEARTBEAT_INTERVAL: "30"
  JOB_POLL_INTERVAL: "5"

---
# NOTE: Create this secret manually with your actual API key
# kubectl create secret generic cloudops-agent-secret \
#   --from-literal=API_KEY=your-actual-api-key \
#   -n cloudops-agent
apiVersion: v1
kind: Secret
metadata:
  name: cloudops-agent-secret
  namespace: cloudops-agent
  labels:
    app.kubernetes.io/name: cloudops-agent
type: Opaque
data:
  # Base64 encoded placeholder - REPLACE WITH YOUR ACTUAL KEY
  # To encode: echo -n 'your-api-key' | base64
  API_KEY: eW91ci1hcGkta2V5LWhlcmU=

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudops-agent-work
  namespace: cloudops-agent
  labels:
    app.kubernetes.io/name: cloudops-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudops-agent-logs
  namespace: cloudops-agent
  labels:
    app.kubernetes.io/name: cloudops-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudops-agent
  namespace: cloudops-agent
  labels:
    app.kubernetes.io/name: cloudops-agent
    app.kubernetes.io/component: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudops-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudops-agent
    spec:
      serviceAccountName: cloudops-agent
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: cloudops-agent
          # IMPORTANT: Update with your ACR image
          image: your-acr.azurecr.io/cloudops-agent:1.0.0
          imagePullPolicy: IfNotPresent
          args:
            - "run"
            - "--url"
            - "$(API_URL)"
            - "--api-key"
            - "$(API_KEY)"
            - "--pool"
            - "$(POOL_ID)"
            - "--max-jobs"
            - "$(MAX_PARALLEL_JOBS)"
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: cloudops-agent-config
                  key: API_URL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudops-agent-secret
                  key: API_KEY
            - name: POOL_ID
              valueFrom:
                configMapKeyRef:
                  name: cloudops-agent-config
                  key: POOL_ID
            - name: MAX_PARALLEL_JOBS
              valueFrom:
                configMapKeyRef:
                  name: cloudops-agent-config
                  key: MAX_PARALLEL_JOBS
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: work
              mountPath: /app/work
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: work
          persistentVolumeClaim:
            claimName: cloudops-agent-work
        - name: logs
          persistentVolumeClaim:
            claimName: cloudops-agent-logs
      # Optional: Add image pull secret for private ACR
      # imagePullSecrets:
      #   - name: acr-secret

---
# Optional: RBAC for kubectl access from agent pods
# Uncomment if your jobs need to interact with Kubernetes
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: cloudops-agent-role
#   namespace: cloudops-agent
# rules:
#   - apiGroups: ["apps"]
#     resources: ["deployments"]
#     verbs: ["get", "list", "patch"]
#   - apiGroups: [""]
#     resources: ["pods"]
#     verbs: ["get", "list", "delete"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: cloudops-agent-rolebinding
#   namespace: cloudops-agent
# subjects:
#   - kind: ServiceAccount
#     name: cloudops-agent
#     namespace: cloudops-agent
# roleRef:
#   kind: Role
#   name: cloudops-agent-role
#   apiGroup: rbac.authorization.k8s.io
